// Question 3:
Promise.reject("Error occurred").catch((err) => console.log(err));

// Output:
// Error occurred
